//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demotest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name Required!")]
 
      
        [StringLength(30, MinimumLength = 4,
                  ErrorMessage = "Name should be between 4 and 30 characters")]
    
        public string Name { get; set; }
        [Required(ErrorMessage = "Email Required!")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        [Required]
        public int StateId { get; set; }
        [Required]
        public int CityId { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public bool Agree { get; set; }
    }
}
